// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.github.net.grpc.dto;

public interface OrderIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.net.grpc.dto.OrderId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();
}
