// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.github.net.grpc.dto;

public final class OrderApi {
  private OrderApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\"\025\n\007OrderId\022\n\n\002id\030\001 \001(\005\"Y\n\010" +
      "OrderDTO\022\014\n\004name\030\001 \001(\t\022\017\n\007address\030\002 \001(\t\022" +
      "\017\n\007buyDate\030\003 \001(\t\022\035\n\010products\030\004 \003(\0132\013.Pro" +
      "ductDTO\"*\n\nProductDTO\022\n\n\002id\030\001 \001(\005\022\020\n\010pro" +
      "dName\030\002 \001(\t2{\n\014OrderService\022!\n\010getOrder\022" +
      "\010.OrderId\032\t.OrderDTO\"\000\022!\n\010addOrder\022\t.Ord" +
      "erDTO\032\010.OrderId\"\000\022%\n\nqueryOrder\022\t.OrderD" +
      "TO\032\010.OrderId\"\0000\001B!\n\023com.github.net.grpcB" +
      "\010OrderApiP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OrderId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_OrderDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OrderDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderDTO_descriptor,
        new java.lang.String[] { "Name", "Address", "BuyDate", "Products", });
    internal_static_ProductDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProductDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductDTO_descriptor,
        new java.lang.String[] { "Id", "ProdName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
