// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.github.net.grpc.dto;

public interface OrderDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string address = 2;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>optional string address = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>optional string buyDate = 3;</code>
   */
  java.lang.String getBuyDate();
  /**
   * <code>optional string buyDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getBuyDateBytes();

  /**
   * <code>repeated .ProductDTO products = 4;</code>
   */
  java.util.List<ProductDTO>
      getProductsList();
  /**
   * <code>repeated .ProductDTO products = 4;</code>
   */
  ProductDTO getProducts(int index);
  /**
   * <code>repeated .ProductDTO products = 4;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .ProductDTO products = 4;</code>
   */
  java.util.List<? extends ProductDTOOrBuilder>
      getProductsOrBuilderList();
  /**
   * <code>repeated .ProductDTO products = 4;</code>
   */
  ProductDTOOrBuilder getProductsOrBuilder(
      int index);
}
