// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.github.net.grpc.dto;

public final class OrderApi {
  private OrderApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_net_grpc_OrderId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_net_grpc_OrderId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_net_grpc_OrderDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_net_grpc_OrderDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_net_grpc_ProductDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_net_grpc_ProductDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\022\023com.github.net.grpc\"\025\n\007Or" +
      "derId\022\n\n\002id\030\001 \001(\005\"m\n\010OrderDTO\022\014\n\004name\030\001 " +
      "\001(\t\022\017\n\007address\030\002 \001(\t\022\017\n\007buyDate\030\003 \001(\t\0221\n" +
      "\010products\030\004 \003(\0132\037.com.github.net.grpc.Pr" +
      "oductDTO\"*\n\nProductDTO\022\n\n\002id\030\001 \001(\005\022\020\n\010pr" +
      "odName\030\002 \001(\t2\363\001\n\014OrderService\022I\n\010getOrde" +
      "r\022\034.com.github.net.grpc.dto.OrderId\032\035.com.gi" +
      "thub.net.grpc.OrderDTO\"\000\022I\n\010addOrder\022\035.c" +
      "om.github.net.grpc.OrderDTO\032\034.com.github" +
      ".net.grpc.OrderId\"\000\022M\n\nqueryOrder\022\035.com.",
      "github.net.grpc.OrderDTO\032\034.com.github.ne" +
      "t.grpc.OrderId\"\0000\001B!\n\023com.github.net.grp" +
      "cB\010OrderApiP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_net_grpc_OrderId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_net_grpc_OrderId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_net_grpc_OrderId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_github_net_grpc_OrderDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_net_grpc_OrderDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_net_grpc_OrderDTO_descriptor,
        new java.lang.String[] { "Name", "Address", "BuyDate", "Products", });
    internal_static_com_github_net_grpc_ProductDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_github_net_grpc_ProductDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_net_grpc_ProductDTO_descriptor,
        new java.lang.String[] { "Id", "ProdName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
