// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.github.net.grpc.dto;

public interface ProductDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string prodName = 2;</code>
   */
  java.lang.String getProdName();
  /**
   * <code>optional string prodName = 2;</code>
   */
  com.google.protobuf.ByteString
      getProdNameBytes();
}
